routes/web.php
Route::get('test-temperature',function (){
$data=\App\Models\EmployeeTemperature::whereBetween('temp_date',['2020-09-01','2020-09-04'])->get()->groupBy('employee_id')->toArray();
foreach ($data as $ey=>$val){
    foreach ($val as $k=>$v) {
        $val[$k]['temp_date'] = date('Y-m-d', strtotime($v['temp_date']));

    }
            $date = collect($val)->groupBy('temp_date')->toArray();
            foreach ($date as $d=>$t){
                if(count($t)>1){
                    for($j=0;$j<count($t)-1;$j++){
                        \App\Models\EmployeeTemperature::where('id',$t[$j]['id'])->delete();
                    }
                }
            }
}
return redirect('/');
});

Auth::routes();
Route::post('/login', [
    'uses'          => 'Auth\LoginController@login',
    'middleware'    => 'checkstatus',
]);

Route::get('/', function () {
    if (auth()->check()) {
        return redirect('/dashboard');
    } else {
        return redirect('/login');
    }
});

Route::get('/home', function () {
    return redirect('/dashboard');
});


Route::get('/test-mail', 'CronController@testMail');
Route::get('/cron/guest_user_end', 'CronController@endGuestUser');

/*
   |--------------------------------------------------------------------------
   | Routes Without authentication
   |--------------------------------------------------------------------------
 */
Route::get('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('/password/forgot', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::get('/password/reset/{token}/{email}', 'Auth\ResetPasswordController@showResetForm')->name('password_reset_save');
Route::post('/reset/password', 'Auth\ResetPasswordController@reset')->name('password.reset');


Auth::routes();

Route::get('register_company',['as' => 'company.register', 'uses' => 'RegisterCompanyController@register']);
Route::post('register_company',['as' => 'company.register', 'uses' => 'RegisterCompanyController@registerCreate']);

Route::group(['middleware' => 'auth'], function () {


    Route::group(['namespace' => 'Auth'], function () {

        Route::get('view-profile', 'ProfileController@showProfile')->name('view.profile');
        Route::get('update-profile', 'ProfileController@editProfile')->name('edit.profile');
        Route::post('update-profile', 'ProfileController@updateProfile')->name('update.profile');

        Route::get('change-password', 'ProfileController@changePassword')->name('change.password');
        Route::post('change-password', 'ProfileController@updatePassword')->name('update.password');

        Route::get('edit-address', 'ProfileController@editAddress')->name('address.change');
        Route::post('edit-address', 'ProfileController@updateAddress')->name('update.address');

        Route::get('edit-settings', 'ProfileController@settings')->name('profile.settings');
        Route::post('edit-settings', 'ProfileController@updateSettings')->name('update.settings');

        Route::get('logout', 'LoginController@logout')->name('logout');
    });


    /*
      |--------------------------------------------------------------------------
      | Super Admin Routes
      |--------------------------------------------------------------------------
    */
    Route::group(['namespace' => 'Backend'], function () {

        //After Login redirect to dashboard
        Route::get('dashboard', 'DashboardController@index')->name('dashboard');

        Route::resource('users', 'UserController');
        Route::get('users/delete/{id}', ['as' => 'users.delete', 'uses' => 'UserController@destroy']);

        Route::resource('company', 'CompanyController');
        Route::get('company/delete/{id}', ['as' => 'company.delete', 'uses' => 'CompanyController@destroy']);
        Route::get('company/cancel/{id}', ['as' => 'company.cancel', 'uses' => 'CompanyController@cancel']);
        Route::get('company/block/{id}', ['as' => 'company.block', 'uses' => 'CompanyController@block']);
        Route::post('company/reset_password', ['as' => 'company.reset_password', 'uses' => 'CompanyController@resetPassword']);

        Route::resource('roles', 'RoleController');
        Route::get('roles/delete/{id}', ['as' => 'roles.delete', 'uses' => 'RoleController@destroy']);

        Route::resource('groups', 'GroupController');
        Route::get('groups/delete/{id}', ['as' => 'groups.delete', 'uses' => 'GroupController@destroy']);
        Route::post('groups/get_ajax_data', ['uses' => 'GroupController@get_ajax_data']);
        Route::post('groups/show_people', ['as' => 'groups.show_people','uses' => 'GroupController@show_people']);

        Route::resource('people_registry', 'PeopleRegistryController');
        Route::get('people_registry/delete/{id}', ['as' => 'people_registry.delete', 'uses' => 'PeopleRegistryController@destroy']);
        Route::post('people_registry/show_video/', ['as' => 'people_registry.show_video', 'uses' => 'PeopleRegistryController@show_video']);
        Route::post('people_registry/get_ajax_data/', ['uses' => 'PeopleRegistryController@get_ajax_data']);


        Route::resource('people_attendance', 'PeopleAttendanceController');
        Route::post('people_attendance/get_attendance', ['as' => 'people_registry.get_attendance', 'uses' => 'PeopleAttendanceController@get_attendance']);
        Route::post('people_attendance/ajax-attendance-log', ['as' => 'people_registry.ajax-attendance-log', 'uses' => 'PeopleAttendanceController@ajaxAttendanceLog']);

        Route::resource('devices', 'DeviceController');
        Route::get('devices/delete/{id}', ['as' => 'devices.delete', 'uses' => 'DeviceController@destroy']);
        Route::post('devices/get_ajax_data', ['as' => 'devices.get_ajax_data', 'uses' => 'DeviceController@get_ajax_data']);

        Route::resource('device_people', 'DevicePeopleController');
        Route::post('device_people/get_ajax_data', ['as' => 'device_people.get_ajax_data', 'uses' => 'DevicePeopleController@get_ajax_data']);

        //Route::get('devices/delete/{id}', ['as' => 'devices.delete', 'uses' => 'DeviceController@destroy']);

        Route::get('device_settings/settings', ['as' => 'device_settings.settings', 'uses' => 'DeviceSettingsController@settings']);
        Route::post('device_settings/update_settings/{id}', ['as' => 'device_settings.update_settings', 'uses' => 'DeviceSettingsController@updateSettings']);
        Route::resource('device_settings', 'DeviceSettingsController');



        Route::resource('building', 'BuildingController');
        Route::get('building/delete/{id}', ['as' => 'building.delete', 'uses' => 'BuildingController@destroy']);
        Route::post('building/get_ajax_data', ['as' => 'building.get_ajax_data', 'uses' => 'BuildingController@get_ajax_data']);
        Route::post('building/show_booking', ['as' => 'building.show_booking', 'uses' => 'BuildingController@show_booking']);

        Route::resource('building_policy', 'BuildingPolicyController');
        Route::get('building_policy/delete/{id}', ['as' => 'building_policy.delete', 'uses' => 'BuildingPolicyController@destroy']);

        Route::resource('bookings', 'BookingController');
        Route::post('bookings/get_ajax_data', ['as' => 'bookings.get_ajax_data', 'uses' => 'BookingController@get_ajax_data']);
        Route::get('bookings/delete/{id}', ['as' => 'bookings.delete', 'uses' => 'BookingController@destroy']);


        Route::get('contact_tracing', ['as'=>'contact_tracing.index','uses'=>'ContactTracingController@index']);
        Route::post('getContactTracing', ['as' => 'contact_tracing_data', 'uses' => 'ContactTracingController@getLists']);
        Route::post('contact_tracing/show_contact', ['as' => 'contact_tracing.show_contact', 'uses' => 'ContactTracingController@show']);
        Route::post('contact_tracing/show_other_contact', ['as' => 'contact_tracing.show_other_contact', 'uses' => 'ContactTracingController@show_other']);

        Route::get('risk_report', ['as'=>'risk_report.index','uses'=>'RiskController@index']);
        Route::post('getRiskLists', ['as'=>'risk_data','uses'=>'RiskController@getRiskLists']);

        Route::get('employee/export_data', ['as' => 'employee.export_data', 'uses' => 'EmployeeController@export_data']);
        Route::get('employee/import_data', ['middleware'=>'company_role','as' => 'employee.import_data', 'uses' => 'EmployeeController@import_data']);
        Route::post('employee/import_data_store', ['middleware'=>'company_role','as' => 'employee.import_data_store', 'uses' => 'EmployeeController@import_data_store']);
        Route::resource('employee', 'EmployeeController');
        Route::post('employee/get_ajax_data', 'EmployeeController@get_ajax_data');
        Route::get('employee/delete/{id}', ['as' => 'employee.delete', 'uses' => 'EmployeeController@destroy']);
        Route::get('employee/cancel/{id}', ['as' => 'employee.cancel', 'uses' => 'EmployeeController@cancel']);
        Route::get('employee/block/{id}', ['as' => 'employee.block', 'uses' => 'EmployeeController@block']);

        Route::resource('emp_temp', 'EmployeeTempratureController');
        Route::post('getEmpTemp', ['as' => 'emp_temp_list', 'uses' => 'EmployeeTempratureController@getLists']);
        Route::get('emp_temp/delete/{id}', ['as' => 'emp_temp.delete', 'uses' => 'EmployeeTempratureController@destroy']);


        Route::get('guest_users', ['as' => 'guest_users.index', 'uses' => 'GuestUsersController@index']);
        Route::post('guest_users/getGuestUsers', ['as' => 'guest_users.getGuestUsers', 'uses' => 'GuestUsersController@getLists']);
        Route::post('guest_users/show_video/', ['as' => 'guest_users.show_video', 'uses' => 'GuestUsersController@show_video']);
        Route::get('guest_users/delete/{id}', ['as' => 'guest_users.delete', 'uses' => 'GuestUsersController@destroy']);

app/Http/Controllers/Backend/BuildingAccessController.php
<?php

namespace App\Http\Controllers\Backend;

use App\BuildingAccess;
use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\AddBuildingRequest;
use App\Http\Requests\Backend\UpdateBuildingRequest;
use App\Models\Company;
use App\Repositories\Backend\BuildingAccess\BuildingAccessContract;
use Illuminate\Http\Request;

class BuildingAccessController extends Controller
{
    protected $repository;

    public function __construct(BuildingAccessContract $repository)
    {
        $this->middleware('company_role');
        $this->repository = $repository;
    }


    public function index(){
        return view('backend.building_access.index');
    }
    public function tableAjax(Request $request){
        $buildings=BuildingAccess::where('company_id',auth()->user()->company->id)->get();
        return response()->json(['status'=>1,'success'=>true,'data'=>$buildings],200);
    }

    public function create(){
        return view('backend.building_access.form');
    }

    public function  store(AddBuildingRequest $request)
    {
        try {
            $inputs = $request->except('_token');
            $this->repository->storeBuilding($inputs);
            return  redirect(route('booking-access.index'))->with('success','Building Added!');
        }catch (\Exception $e){
            return redirect(route('booking-access.index'))->with('failure','something went wrong');
        }
    }
    public function edit($id){
       $building= BuildingAccess::where('id',$id)->first();
        return view('backend.building_access.form',compact('building'));
    }

    public function update(UpdateBuildingRequest $request , $id){
        try {
            $data = $request->only('building_name', 'building_limit', 'building_status');
            $this->repository->updateBuilding($id, $data);
            return redirect(route('booking-access.index'))->with('success','Building details updated');
        }catch (\Exception $e){
            return redirect(route('booking-access.index'))->with('failure','something went wrong');
        }
    }

    public function deleteBuilding($id){
        try{
            $this->repository->deleteBuilding($id);
            return redirect(route('booking-access.index'))->with('success','Building removed');
        }
        catch(\Exception $e){
            return redirect(route('booking-access.index'))->with('failure','something went wrong');
        }
    }
}

app/Http/Controllers/Backend/CollisionController.php
<?php

namespace App\Http\Controllers\Backend;

use App\CollisionAccess;
use App\Http\Controllers\Controller;
use Carbon\Carbon;
use Illuminate\Http\Request;

class CollisionController extends Controller
{
    public function index(){
        return view('backend.collision.index');
    }

    public function tableAjax(Request $request)
    {
        //        $collisions=  CollisionAccess::with('fromUser')->where('from_user','171')->get();
        if (!isset($request->date)) {
            $collisions = CollisionAccess::
            //            ->get();
            with('fromUser', 'toUser')->whereHas('fromUser', function ($q) {
                $q->where('deleted_at', '=', null);
            })->whereHas('toUser', function ($q) {
                $q->where('deleted_at', '=', null);
            })->groupBy('from_user')->get();
        }
        else {
            $collisions = CollisionAccess::with('fromUser', 'toUser')
                ->whereDate('contacted_at', Carbon::parse($request->date)->format('Y-m-d'))
                ->with('fromUser', 'toUser')
                ->whereHas('fromUser', function ($q) {
                    $q->where('deleted_at', '=', null);
                })
                ->whereHas('toUser', function ($q) {
                    $q->where('deleted_at', '=', null);
                })
                ->orderBy('id', 'desc')
                ->groupBy('from_user')
                ->get();
        }
        //       dd(collect($collisions)->toArray());
        //        with(array('fromUser'=>function($query){
        //            $query->select('id','first_name');
        //        }))->with(array('toUser'=>function($query){
        //            $query->select('id','first_name');
        //        }))
        $colllect = collect($collisions)->where('fromUser.company_id', auth()->user()->company->id)->values();
        //       dd($colllect);
        //dd($colllect);
        return response()->json([
            'status' => 1,
            'data'   => $colllect
        ]);
    }

    public function details($id,$date){
//dd($date);
//       dd($data);
return view('backend.collision.view',compact('id','date'));
    }
    public function viewTable(Request $request){
//        dd($request->all());
        $data= CollisionAccess::with('toUser')->where('from_user',$request->id)->whereDate('contacted_at',Carbon::parse($request->date))->get();
//        dd(collect($data)->where());
        return response()->json(['status'=>1,'data'=>$data]);
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Repositories\Backend\Dashboard\DashboardContract;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Auth;

class DashboardController extends Controller {

    protected $repository;

    public function __construct(DashboardContract $repository) {
        $this->repository = $repository;
    }

    //return all the reservation record from database
    public function index() {
        try {
            $user_count = User::all()->count();
            if (Auth::user()->hasRole('admin')) {
                $today_guest_count = \App\Models\GuestUser::where('from_date', '<=', date('Y-m-d'))
                                ->where('to_date', '>=', date('Y-m-d'))->get()->count();

                $avg_tempreture = \App\Models\EmployeeTemperature::selectRaw('avg(temperature) as temp')->whereDate('temp_date', date('Y-m-d'))->first();
            } else {
                $getUserCompany = \App\Models\Company::where('user_id', Auth::user()->id)->first();
                $today_guest_count = \App\Models\GuestUser::where('from_date', '<=', date('Y-m-d'))
                                ->where('to_date', '>=', date('Y-m-d'))
                                ->where('company_id', $getUserCompany->id)->get()->count();
                $avg_tempreture = \App\Models\EmployeeTemperature::selectRaw('avg(temperature) as temp')
                                ->leftJoin('employee', 'employee.id', '=', 'employee_temperature.employee_id')
                                ->leftJoin('guest_users', 'guest_users.id', '=', 'employee_temperature.employee_id')
                                ->leftJoin('companies as emp_comp', 'employee.company_id', '=', 'emp_comp.id')
                                ->leftJoin('companies as guest_comp', 'guest_users.company_id', '=', 'guest_comp.id')
                                ->where(function($query) use($getUserCompany) {
                                    $query->where('emp_comp.id', $getUserCompany->id);
                                    $query->orWhere('guest_comp.id', $getUserCompany->id);
                                })
                                ->whereDate('temp_date', date('Y-m-d'))->first();
            }
                      
            return view('backend.dashboard', compact('user_count','avg_tempreture','today_guest_count'));
        } catch (\Exception $e) {
            Log::error('Dashboard error:' . $e->getMessage());
            return redirect()->route('dashboard')->with('failure', 'Something went wrong');
        }
    }

}

resources/views/backend/risk_report/form.blade.php
@extends('backend.layouts.master')
@section('content')
    <div class="main d-flex flex-column flex-row-fluid">
        <!--begin::Subheader-->
        <div class="subheader py-2 py-lg-4" id="kt_subheader">
            <div class="w-100 d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
                <!--begin::Info-->
                <div class="d-flex align-items-center flex-wrap mr-1">
                    <!--begin::Page Heading-->
                    <div class="d-flex align-items-baseline mr-5">
                        <!--begin::Page Title-->
                        <h5 class="text-dark font-weight-bold my-2 mr-5"> {!! isset($emp_temp) ? 'Update People Tempreture' : 'Add People Tempreture' !!}</h5>
                        <!--end::Page Title-->
                        <!--begin::Breadcrumb-->
                        <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
                            <li class="breadcrumb-item">
                                <a href="{{ route('employee.index') }}" class="text-muted">People</a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="{{ isset($emp_temp) ? route('emp_temp.update',$emp_temp->id) : route('emp_temp.create') }} " class="text-muted">{!! isset($emp_temp) ? 'Update People Tempreture' : 'Add People Tempreture' !!}</a>
                            </li>
                        </ul>
                        <!--end::Breadcrumb-->
                    </div>
                    <!--end::Page Heading-->
                </div>
                <!--end::Info-->
                <!--begin::Toolbar-->
                <div class="d-flex align-items-center">
                    <!--begin::Daterange-->
                    <a href="javascript:void(0)" class="btn btn-light-primary btn-sm font-weight-bold mr-2" id="" data-toggle="tooltip" title="" data-placement="left">
                        <span class="opacity-60 font-weight-bold mr-2" id="">Today</span>
                        <span class="font-weight-bold" id="">{{ date('M d', strtotime(now())) }}</span>
                    </a>
                    <!--end::Daterange-->
                    <!--begin::Dropdown-->

                    <!--end::Dropdown-->
                </div>
                <!--end::Toolbar-->
            </div>
        </div>
        <!--end::Subheader-->
        <div class="content flex-column-fluid" id="kt_content">
            <div class="row">
                <div class="col-lg-12">
                    <!--begin::Card-->
                    <div class="card card-custom gutter-b example example-compact">
                        <div class="card-header">
                            <h3 class="card-title">{!! isset($emp_temp) ? 'Update People Tempreture' : 'Add People Tempreture' !!} </h3>

                        </div>
                        <!--begin::Form-->
                        <form id="companyForm" class="form m-form m-form--fit m-form--label-align-right"
                              action="{{ isset($emp_temp) ? route('emp_temp.update', $emp_temp->id) : route('emp_temp.store')}}"
                              method="POST" enctype="multipart/form-data">
                            @csrf
                            @if(isset($emp_temp))
                                @method('PUT')
                            @endif
                            <div class="card-body">

                                <div class="row">
                                    <div class="form-group col-lg-6">
                                        <label class="form-control-label">People</label>
                                        <select class="form-control" name="employee_id">
                                            <option value="">Select People</option>
                                           @if($employees)
                                                @foreach($employees as $emp)
                                                    <option value="{{ $emp->id }}">{{ $emp->first_name . ' ' .$emp->last_name.' ( '.$emp->email.')' }}</option>
                                                @endforeach
                                           @endif
                                        </select>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-lg-6">
                                        <label class="form-control-label">Temperature</label>
                                        <input type="text" name="temperature" class="form-control" value="{!! old('temperature') !!}">
                                        {{--<div class="radio-inline">
                                            @php $statusArry = ['Red','Green'];@endphp
                                            @foreach($statusArry as $status)
                                                <label class="radio">
                                                    <input type="radio" name="temperature" value="{{$status}}"/> {{ $status }}
                                                    <span></span>
                                                </label>
                                            @endforeach
                                        </div>--}}
                                    </div>
                                </div>

                            </div>
                            <!--end::Code example-->
                            <div class="card-footer">
                                <button type="submit" class="btn btn-success font-weight-bold mr-2">Submit</button>
                                <button type="button" class="btn btn-light-success font-weight-bold" onclick="return window.location.href='{{ route('emp_temp.index') }}'">Cancel</button>
                            </div>
                        </form>
                        <!--end::Form-->
                    </div>
                    <!--end::Card-->
                    <!--begin::Card-->

                    <!--end::Card-->
                </div>

            </div>
        </div>
        <!--end::Content-->
    </div>
@endsection

@section('scripts')
    <script>
        var KTFormControls = function () {
            // Private functions
            var _initDemo1 = function () {
                FormValidation.formValidation(
                    document.getElementById('companyForm'),
                    {
                        fields: {
                            employee_id: {
                                validators: {
                                    notEmpty: {
                                        message: 'People is required'
                                    },

                                }
                            },
                            temperature: {
                                validators: {
                                    notEmpty: {
                                        message: 'Temperature is required'
                                    },
                                    numeric: {
                                        message: 'Temperature value is not a number',
                                        // The default separators
                                        thousandsSeparator: '',
                                        decimalSeparator: '.'
                                    }

                                }
                            },

                        },

                        plugins: { //Learn more: https://formvalidation.io/guide/plugins
                            trigger: new FormValidation.plugins.Trigger(),
                            // Bootstrap Framework Integration
                            bootstrap: new FormValidation.plugins.Bootstrap(),
                            // Validate fields when clicking the Submit button
                            submitButton: new FormValidation.plugins.SubmitButton(),
                            // Submit the form when all fields are valid
                            defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
                        }
                    }
                );
            }
            return {
                // public functions
                init: function() {
                    _initDemo1();

                }
            };
        }();

        jQuery(document).ready(function() {
            KTFormControls.init();
        });


    </script>
@endsection

resources/views/backend/risk_report/show.blade.php
<div class="card card-custom">
    <!--begin::Header-->
    <div class="card-header h-auto">
        <div class="card-title">
            <h3 class="card-label">Basic Detail</h3>
        </div>
    </div>
    <!--end::Header-->
    <!--begin::Body-->
    <div class="card-body py-4">
        <div class="form-group row my-2">
            <label class="col-4 col-form-label">Name:</label>
            <div class="col-8">
                <span class="form-control-plaintext font-weight-bolder">{{ $employee->first_name }} {{ $employee->last_name }}</span>
            </div>
        </div>
        <div class="form-group row my-2">
            <label class="col-4 col-form-label">Email:</label>
            <div class="col-8">
                <span class="form-control-plaintext font-weight-bolder">{{ $employee->email }}</span>
            </div>
        </div>
        {{--
        <div class="form-group row my-2">
            <label class="col-4 col-form-label">Phone:</label>
            <div class="col-8">
                <span class="form-control-plaintext font-weight-bolder">+456 7890456</span>
            </div>
        </div>--}}
    </div>
</div>
<div class="card card-custom">
    <div class="card-header h-auto">
        <div class="card-title">
            <h3 class="card-label">Contacted Users</h3>
        </div>
    </div>
    <div class="card-body py-4">
        @if(!empty($contact_tracing_user))
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">First Name</th>
                    <th scope="col">Last Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Date</th>
                </tr>
                </thead>
                <tbody>
                @foreach($contact_tracing_user as $key=>$cuser)

                    @if (!empty($cuser->employee) && $cuser->employee->id != $employee->id)
                        <tr>
                            <th scope="row">{{$key+1}}</th>
                            <td>
                                {{ $cuser->employee->first_name }}
                            </td>
                            <td>
                                {{ $cuser->employee->last_name }}
                            </td>
                            <td>
                                {{ $cuser->employee->email }}
                            </td>
                            <td>
                                {{ date("d-M-Y",strtotime($cuser->contact_time)) }}
                            </td>
                        </tr>
                    @elseif( !empty($cuser->contact_employee) && $cuser->contact_employee->id != $employee->id)
                        <tr>
                            <th scope="row">{{$key+1}}</th>
                            <td>
                                {{ $cuser->contact_employee->first_name }}
                            </td>
                            <td>
                                {{ $cuser->contact_employee->last_name }}
                            </td>
                            <td>
                                {{ $cuser->contact_employee->email }}
                            </td>
                            <td>
                                {{ date("d-M-Y",strtotime($cuser->contact_time)) }}
                            </td>
                        </tr>
                    @endif
                @endforeach
                </tbody>
            </table>
        @endif
    </div>
</div>